//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SlackerRankData.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public string Email { get; set; }
        public int NumberRight { get; set; }
        public int NumberWrong { get; set; }
        public int QuestionNumber { get; set; }
        public int TableID { get; set; }
    
        public virtual Challenge Challenge { get; set; }
        public virtual NonAdmin NonAdmin { get; set; }
    }
}
