// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SlackerRank_preAlpha.Data;
using System;

namespace SlackerRank_preAlpha.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20170925133516_test2")]
    partial class test2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SlackerRank_preAlpha.Models.TeacherCodeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CodeExe");

                    b.Property<string>("CodeIntro");

                    b.Property<string>("CodePath");

                    b.Property<string>("CodeSolution");

                    b.HasKey("Id");

                    b.ToTable("TeacherCode");
                });
#pragma warning restore 612, 618
        }
    }
}
